#!/bin/bash

APP_NAME=mhbridge
APP_HOME=/usr/local/mhbridge
APP_JAR=mhbridge-1.0.1-jar-with-dependencies.jar
APP_MAIN=org.capybara.mhbridge.MhBridge

export JAVA_HOME=/usr/java/default

MAC=`ifconfig eth0 | grep HWaddr | awk '{ print $5 }' | sed 's/://g'`
PATH=$PATH:$JAVA_HOME/bin

export TZ=:`cat /etc/timezone`

start() {
    echo -n $"Starting ${APP_NAME}: "
        APP_CLASSPATH=${APP_HOME}/${APP_JAR}
        cd ${APP_HOME}
        /usr/local/bin/jsvc -pidfile /var/run/${APP_NAME}.pid -wait 20 -classpath "${APP_CLASSPATH}" ${APP_MAIN}
        rc=$?
        if [ "$rc" -ne "0" ] ; then
                echo "FAILED"
        else
                echo "OK"
        fi
}

stop() {
        echo -n $"Stopping ${APP_NAME}: "
        /usr/local/bin/jsvc -pidfile /var/run/${APP_NAME}.pid -stop ${APP_MAIN}
        echo "OK"
}


case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 1
esac

exit 0
